// deno-lint-ignore no-unused-vars
import { assertEquals, assertThrows } from "@std/assert";
import { Day08 } from "@/day08/Day08.ts";

const dayImpl = new Day08();

Deno.test("test part 1", () => {
    const input = dayImpl.getInput(true, 1);
    const result = dayImpl.solvePart1(input);
    assertEquals(result, "14");
});

Deno.test("test part 2", () => {
    const result = dayImpl.solvePart2(`T....#....
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
`);
    assertEquals(result, "9");
});

Deno.test("test part 2", () => {
    const input = dayImpl.getInput(true, 2);
    const result = dayImpl.solvePart2(input);
    assertEquals(result, "34");
});
